- name: Install remi-release-8.rpm using yum
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true
  
- name: Enable Redis 6.2 from package streams
  ansible.builtin.command: dnf module enable redis:remi-6.2 -y

- name: Install redis 6.2
  ansible.builtin.package:
    name: redis
    state: present
  
- name: Give remote access connection
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start and enable nginx
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes