- name: Configure YUM Repos from the script
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure YUM Repos for RabbitMQ.
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Install RabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Start and enable rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes
  
- name: RabbitMQ username / password creation
  ansible.builtin.command: "rabbitmqctl add_user {{rmq_user}} {{rmq_password}}"

- name: Set permissions
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"