- name: Disable the current mysql version
  ansible.builtin.command: dnf module disable mysql -y

- name: Copy the mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Start and Enable MqSQLservice
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Setup root password to MySQL
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1