- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"

- name: remove old application code
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create directory app
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download the {{component}} application"
  tags:
  - deployment
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
  
- name: "Unzip {{component}}.zip to /app directory"
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes

- name: Install dependencies
  tags:
  - deployment
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: "Restart {{component}} service"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted