- name: Copy the mongo.repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: "get the catalogue entries count"
  ansible.builtin.shell:  mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"

- name: "get the user entries count"
  ansible.builtin.shell:  mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: users_count
  when: component == "user"

- name: print entries catalogue count
  ansible.builtin.debug:
    msg: "Count: {{products_count.stdout}}"
  when: component == "catalogue"

- name: print entries user count
  ansible.builtin.debug:
    msg: "Count: {{users_count.stdout}}"
  when: component == "user"

- name: "load catalogue data"
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: component == "catalogue" and products_count.stdout == "0"  # keep double quotes
  #ignore_errors: true

- name: "load user data"
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: component == "user" and users_count.stdout == "0"  # keep double quotes
  #ignore_errors: true